# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_organization_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
